### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by joshpetit** [rhysd/dotfiles#10] opened 2022-05-11 14:56 UTC
Hey! I'm trying to install this, but receive this error when running `go get`:

```
cannot find package "github.com/google/go-github/v30/github" in any of:
        /usr/lib/go/src/github.com/google/go-github/v30/github (from $GOROOT)
        /home/joshu/go/src/github.com/google/go-github/v30/github (from $GOPATH)
```

Any help would be appreciated!

**Comment by rhysd** [comment] 2022-05-11 23:51
It's an outdated instruction since behavior of `go get` changed in recent Go. Can you try the following command?

```
go install github.com/rhysd/dotfiles
```

**Comment by rhysd** [comment] 2022-05-17 08:19
I confirmed the above command worked. Closing.

**Closed** 2022-05-17 08:19 UTC

**Comment by joshpetit** [comment] 2022-05-18 04:36
Hey! sorry for the delayed response, I tried the command and got this error:
```
go/src/github.com/rhysd/go-github-selfupdate/selfupdate/detect.go:10:2: cannot find package "github.com/google/go-github/v30/github" in any of:
        /usr/lib/go/src/github.com/google/go-github/v30/github (from $GOROOT)
        /home/joshu/go/src/github.com/google/go-github/v30/github (from $GOPATH)
```
